//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeedBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FeedInfo&gt;
        ///    &lt;Transform&gt;&lt;![CDATA[&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;&lt;xsl:value-of select=&quot;//rss/channel/title&quot;  disable-output-escaping=&quot;yes&quot;/&gt;&lt;/h1&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;&lt;xsl:value-of select=&quot;//rss/channel/description&quot; disable-output-escaping=&quot;yes&quot;/&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;xsl:value-of sele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdditionalFeedData {
            get {
                return ResourceManager.GetString("AdditionalFeedData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeleteIcon {
            get {
                object obj = ResourceManager.GetObject("DeleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileIcon {
            get {
                object obj = ResourceManager.GetObject("FileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderIcon {
            get {
                object obj = ResourceManager.GetObject("FolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation1 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation2 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation3 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation4 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation5 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation6 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPAnimation7 {
            get {
                object obj = ResourceManager.GetObject("FTPAnimation7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPConnected {
            get {
                object obj = ResourceManager.GetObject("FTPConnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FTPDisconnected {
            get {
                object obj = ResourceManager.GetObject("FTPDisconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreyXsmall {
            get {
                object obj = ResourceManager.GetObject("GreyXsmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;languages&gt;
        ///	&lt;language name=&quot;Afrikaans&quot; code=&quot;af&quot; /&gt;
        ///	&lt;language name=&quot;Albanian&quot; code=&quot;sq&quot; /&gt;
        ///	&lt;language name=&quot;Basque&quot; code=&quot;eu&quot; /&gt;
        ///	&lt;language name=&quot;Belarusian&quot; code=&quot;be&quot; /&gt;
        ///	&lt;language name=&quot;Bulgarian&quot; code=&quot;bg&quot; /&gt;
        ///	&lt;language name=&quot;Catalan&quot; code=&quot;ca&quot; /&gt;
        ///	&lt;language name=&quot;Chinese (Simplified)&quot; code=&quot;zh-cn&quot; /&gt;
        ///	&lt;language name=&quot;Chinese (Traditional)&quot; code=&quot;zh-tw&quot; /&gt;
        ///	&lt;language name=&quot;Croatian&quot; code=&quot;hr&quot; /&gt;
        ///	&lt;language name=&quot;Czech&quot; code=&quot;cs&quot; /&gt;
        ///	&lt;language name=&quot;Danish&quot; code=&quot;da&quot; /&gt;
        ///	&lt;language name=&quot;Dutc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;
        ///    xmlns:itunes=&quot;http://www.itunes.com/dtds/podcast-1.0.dtd&quot; version=&quot;2.0&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;New Item&lt;/title&gt;
        ///&lt;description&gt;Newly created feed item.&lt;/description&gt;
        ///&lt;link&gt;&lt;/link&gt;
        ///&lt;enclosure url=&quot;&quot; length=&quot;&quot; type=&quot;audio/mpeg&quot;&gt;&lt;/enclosure&gt;
        ///&lt;guid isPermaLink=&quot;false&quot;&gt;&lt;/guid&gt;
        ///&lt;pubDate&gt;&lt;/pubDate&gt;
        ///&lt;itunes:subtitle&gt;&lt;/itunes:subtitle&gt;
        ///&lt;itunes:summary&gt;&lt;/itunes:summary&gt;
        ///&lt;itunes:duration&gt;&lt;/itunes:duration&gt;
        ///&lt;itunes:au [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewItemTemplate {
            get {
                return ResourceManager.GetString("NewItemTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap OpenIcon {
            get {
                object obj = ResourceManager.GetObject("OpenIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;
        ///    xmlns:itunes=&quot;http://www.itunes.com/dtds/podcast-1.0.dtd&quot; version=&quot;2.0&quot;&gt;
        ///&lt;channel&gt;
        ///    &lt;title&gt;New Feed&lt;/title&gt;
        ///    &lt;description&gt;&lt;/description&gt;
        ///    &lt;link&gt;&lt;/link&gt;
        ///    &lt;language&gt;en-us&lt;/language&gt;
        ///    &lt;copyright&gt;&lt;/copyright&gt;
        ///    &lt;lastBuildDate&gt;&lt;/lastBuildDate&gt;
        ///    &lt;pubDate&gt;&lt;/pubDate&gt;
        ///    &lt;image&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;description&gt;&lt;/description&gt;
        ///        &lt;url&gt;&lt;/url&gt;
        ///        &lt;link&gt;&lt;/link&gt;
        ///    &lt;/image&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PodcastTemplate {
            get {
                return ResourceManager.GetString("PodcastTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RedXsmall {
            get {
                object obj = ResourceManager.GetObject("RedXsmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_97252 {
            get {
                object obj = ResourceManager.GetObject("refresh_97252", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A|Alpha Time Zone|Military|UTC +01:00 hour|+1
        ///ADT|Atlantic Daylight Time|Atlantic|UTC -03:00 hours|-3
        ///ADT|Atlantic Daylight Time|North America|UTC -03:00 hours|-3
        ///AFT|Afghanistan Time|Asia|UTC +4:30 hours|+4.5
        ///AKDT|Alaska Daylight Time|North America|UTC -08:00 hours|-8
        ///AKST|Alaska Standard Time|North America|UTC -09:00 hours|-9
        ///ALMT|Alma-Ata Time|Asia|UTC +06:00 hours|+6
        ///AMST|Armenia Summer Time|Asia|UTC +05:00 hours|+5
        ///AMST|Amazon Summer Time|South America|UTC -03:00 hours|-3
        ///AMT|Armenia Time|Asia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeZones {
            get {
                return ResourceManager.GetString("TimeZones", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap XMLIcon {
            get {
                object obj = ResourceManager.GetObject("XMLIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///&lt;rss  xmlns:itunes=&quot;http://www.itunes.com/dtds/podcast-1.0.dtd&quot; version=&quot;2.0&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///&lt;channel&gt;
        ///
        ///    &lt;title&gt;&lt;xsl:value-of select=&quot;//rss/channel/title&quot;/&gt;&lt;/title&gt;
        ///    &lt;description&gt;&lt;xsl:value-of select=&quot;//rss/channel/description&quot;/&gt;&lt;/description&gt;
        ///    &lt;link&gt;&lt;xsl:value-of select=&quot;//rss/channel/description&quot;/&gt;&lt;/link&gt;
        ///    &lt;la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSLTAddItunes {
            get {
                return ResourceManager.GetString("XSLTAddItunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///&lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///&lt;channel&gt;
        ///
        ///    &lt;title&gt;&lt;xsl:value-of select=&quot;//rss/channel/title&quot;/&gt;&lt;/title&gt;
        ///    &lt;description&gt;&lt;xsl:value-of select=&quot;//rss/channel/description&quot;/&gt;&lt;/description&gt;
        ///    &lt;link&gt;&lt;xsl:value-of select=&quot;//rss/channel/description&quot;/&gt;&lt;/link&gt;
        ///    &lt;language&gt;&lt;xsl:value-of select=&quot;//rss/channel/language&quot;/&gt;&lt;/language&gt;
        ///    &lt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSLTRemoveItunes {
            get {
                return ResourceManager.GetString("XSLTRemoveItunes", resourceCulture);
            }
        }
    }
}
